project:
  type: website

website:
  title: "ISSS624 Applied Geospatial Analytics"
  navbar:
    left:
    - text: "Syllabus"
      href: syllabus.qmd
    - text: "Lesson Plan"
      href: lesson.qmd
    - text: "Take-home Exercise"
      menu:
      - text: "Take-home Exercise 1"
        href: Take-home_Ex01.qmd
      - text: "Take-home Exercise 2"
        href: Take-home_Ex02.qmd
      - text: "Take-home Exercise 3"
        href: Take-home_Ex03.qmd
    right:
    - text: "Resources"
      href: resources.qmd
    - text: "Home"
      href: index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

