---
title: "Lesson 5: Geograpgically Weighted Logistic Regression (GWLR) and Application"
date: "`r Sys.Date()`"
format: html
---

## Overview

In this lesson, you will learn the basic concepts and methods of logistic regression specially designed for geographical data. Upon completion of this lesson, you will able to:

-   explain the similarities and differences between Logistic Regression (LR) algorithm versus geographical weighted Logistic Regression (GWLR) algorithm.
-   calibrate predictive models by using appropriate Geographically Weighted Logistic Regression algorithm for geographical data.

## Content

-   Basic concepts and principles of Logistic Regression
-   Geographically Weighted Logistic Regression methods
    -   Weighting functions (kernel)
    -   Weighting schemes
    -   Bandwidth
    -   Interpreting and Visualising

## Self-reading Before Meet-up

To read before class:

-   Atkinson PM, German SE, Sear DQ and Clark MJ (2003) ["Exploring the relations between riverbank erosion and geomorphological controls using geographically weighted logistic regression"](https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1538-4632.2003.tb01101.x). *Geographical Analysis* 35(1): 58--82.

## References

-   Schultz, C. et. al. (2016) "Comparison of spatial and aspatial logistic regression models for landmine risk mapping", *Applied Geography* 66, pp. 52-63. Available in SMU eLibrary.

- Varun Narayan Mishra et. al. (2021) "Geographically Weighted Method Integrated with Logistic Regression
for Analyzing Spatially Varying Accuracy Measures of Remote Sensing
Image Classification". *Journal of the Indian Society of Remote Sensing*, 49(5):1189–1199. Available in SMU eLibrary.

- Helen J Mayfield et. al (2018) ["Use of geographically weighted logistic regression to quantify spatial variation in the environmental and sociodemographic drivers of leptospirosis in Fiji: a modelling study"](https://pubmed.ncbi.nlm.nih.gov/29709286/). *Lancet Planet Health* 2: pp. 223–232. 

- Felix Ndidi Nkeki, Monday Ohi Asikhia (2019) "Geographically weighted logistic regression approach to explore the spatial variability in travel behaviour and built environment interactions: Accounting simultaneously for demographic and socioeconomic characteristics" *Applied Geography*, Vol. 108, Pp. 47-63. Available in SMU eLibrary.

- Han Li, Ye Hua Dennis Wei and Zhiji Huang (2014) ["Urban Land Expansion and Spatial Dynamics in Globalizing Shanghai"](https://www.mdpi.com/2071-1050/6/12/8856), *Sustainability* 6, 8856-8875.

## All About R

-   [**GWmodel**](https://cran.r-project.org/web/packages/GWmodel/) package, especially
    -   Gollini, I et. al. (2015) ["GWmodel: An R Package for Exploring Spatial Heterogeneity Using Geographically Weighted Models"](https://www.jstatsoft.org/article/view/v063i17), *Journal of Statistical Software*, Volume 63, Issue 17 and
    -   Binbin Lu, Paul Harris, Martin Charlton & Chris Brunsdon (2014) ["The GWmodel R package: further topics for exploring spatial heterogeneity using geographically weighted models"](https://www.tandfonline.com/doi/full/10.1080/10095020.2014.917453), *Geo-spatial Information Science*, 17:2, 85-101, DOI: 10.1080/10095020.2014.917453.
